version: 2.1
workflows:
  testing:
    jobs:
      - runner-test-should-not-work
jobs:
  runner-test-should-not-work:
    machine: true
    resource_class: large
    parallelism: 10 
    steps:
      - run: echo "Hi I'm on Runners! "
      - run:
          command: sleep 1